python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/blackscholes_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/blackscholes_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_blackscholes_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/bodytrack_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/bodytrack_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_bodytrack_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/canneal_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/canneal_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_canneal_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/dedup_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/dedup_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_dedup_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/ferret_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/ferret_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_ferret_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/fluidanimate_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/fluidanimate_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_fluidanimate_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/freqmine_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/freqmine_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_freqmine_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/streamcluster_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/streamcluster_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_streamcluster_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/swaptions_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/swaptions_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_swaptions_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/vips_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/vips_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_vips_LRU_prp.csv

python Relative_Lifetime.py 1_LRU/Output/1_Write_Count/Intraset_Variations/x264_LRU_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/x264_prp_Intraset.csv > Relative_Lifetime_LRU_PS/Relative_Lifetime_x264_LRU_prp.csv

