python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/blackscholes_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/blackscholes_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_blackscholes_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/bodytrack_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/bodytrack_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_bodytrack_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/canneal_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/canneal_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_canneal_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/dedup_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/dedup_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_dedup_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/ferret_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/ferret_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_ferret_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/fluidanimate_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/fluidanimate_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_fluidanimate_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/freqmine_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/freqmine_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_freqmine_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/streamcluster_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/streamcluster_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_streamcluster_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/swaptions_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/swaptions_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_swaptions_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/vips_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/vips_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_vips_EW_PRP.csv

python Relative_Lifetime.py 2_EqualWrites/Output/1_Write_Count/Intraset_Variations/x264_EqualWrites_Intraset.csv 3_Proposed_Solution/Output/1_Write_Count/Intraset_Variations/x264_prp_Intraset.csv > Relative_Lifetime_EW_PS/Relative_Lifetime_x264_EW_PRP.csv

