python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/blackscholes_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/blackscholes_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_blackscholes_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/bodytrack_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/bodytrack_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_bodytrack_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/canneal_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/canneal_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_canneal_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/dedup_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/dedup_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_dedup_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/facesim_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/facesim_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_facesim_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/ferret_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/ferret_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_ferret_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/fluidanimate_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/fluidanimate_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_fluidanimate_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/freqmine_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/freqmine_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_freqmine_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/streamcluster_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/streamcluster_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_streamcluster_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/swaptions_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/swaptions_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_swaptions_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/vips_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/vips_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_vips_LRU_EqualWrites.csv

python Relative_Lifetime.py 1_LRU_B/Output/1_Write_Count/Intraset_Variations/x264_LRU_Intraset.csv 3_EqualWrites_B/Output/1_Write_Count/Intraset_Variations/x264_EqualWrites_Intraset.csv > Relative_Lifetime_LRU_EW_B/Relative_Lifetime_x264_LRU_EqualWrites.csv

